// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  // Agrega este bloque para el seed:
  migrations: {
    seed: 'pnpm dlx tsx prisma/seed.ts',
  },
  // Mantén el datasource que ya tenías configurado ahí:
  datasource: {
    url: process.env.DATABASE_URL,
  },
});
